// wedding-vue/src/components/layout/Sidebar.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { SidebarLink } from '@/types/navigation'
import logoImage from '@/assets/logo.png'

const props = defineProps<{
  collapsed: boolean
  publicLinks: SidebarLink[]
  protectedLinks: SidebarLink[]
  currentUser?: { nickname: string; profileImageUrl?: string | null } | null
}>()

const emit = defineEmits<{
  toggle: []
  navigate: [link: SidebarLink]
}>()

const isHoveringButton = ref(false)

function handleButtonMouseEnter() {
  isHoveringButton.value = true
}

function handleButtonMouseLeave() {
  isHoveringButton.value = false
}
</script>

<template>
  <aside :class="['sidebar', { collapsed, 'button-hover': isHoveringButton && collapsed }]">
    <div class="sidebar-header">
      <img :src="logoImage" alt="PromiseMarry Lab Logo" class="logo-image" />
      <strong>PromiseMarry Lab</strong>
      <button
        class="sidebar-expand-btn"
        type="button"
        :aria-label="collapsed ? '사이드바 펼치기' : '사이드바 접기'"
        :title="collapsed ? '사이드바 펼치기' : '사이드바 접기'"
        @click="emit('toggle')"
        @mouseenter="handleButtonMouseEnter"
        @mouseleave="handleButtonMouseLeave"
      >
        <span class="arrow" aria-hidden="true">{{ collapsed ? '»' : '«' }}</span>
      </button>
    </div>

    <nav class="sidebar-menu">
      <!-- 로그인 불필요한 메뉴 -->
      <button
        v-for="item in props.publicLinks"
        :key="item.label"
        class="sidebar-menu-item"
        :class="{ active: item.active }"
        type="button"
        @click="emit('navigate', item)"
      >
        <span class="icon">{{ item.icon }}</span>
        <span class="text">{{ item.label }}</span>
      </button>
    </nav>

    <!-- 구분선: 로그인 불필요 메뉴와 로그인 필요 메뉴 사이 -->
    <div class="sidebar-divider"></div>

    <!-- 로그인 필요한 메뉴 -->
    <nav class="sidebar-menu">
      <div class="sidebar-section-title">주요 기능</div>
      <button
        v-for="item in props.protectedLinks"
        :key="item.label"
        class="sidebar-menu-item"
        :class="{ active: item.active }"
        type="button"
        @click="emit('navigate', item)"
      >
        <span class="icon">{{ item.icon }}</span>
        <span class="text">{{ item.label }}</span>
      </button>
    </nav>

    <div class="sidebar-menu" style="margin-top: auto; padding-top: 0">
      <button
        v-if="currentUser"
        class="sidebar-menu-item"
        type="button"
        style="cursor: pointer"
        @click="emit('open-profile')"
      >
        <span class="icon" style="display: flex; align-items: center; justify-content: center">
          <img
            v-if="currentUser.profileImageUrl"
            :src="currentUser.profileImageUrl"
            alt="프로필"
            style="width: 24px; height: 24px; border-radius: 50%; object-fit: cover"
          />
          <span v-else>👤</span>
        </span>
        <span class="text">{{ currentUser.nickname }}님</span>
      </button>
    </div>
  </aside>
</template>

// wedding-react/src/components/layout/Sidebar.tsx
import React, { useState } from 'react'
import type { SidebarLink } from '@/types/navigation'
import logoImage from '@/assets/logo.png'
import './Sidebar.css'

interface SidebarProps {
  collapsed: boolean
  publicLinks: SidebarLink[]
  protectedLinks: SidebarLink[]
  currentUser?: { nickname: string; profileImageUrl?: string | null } | null
  onToggle: () => void
  onNavigate: (link: SidebarLink) => void
  onOpenProfile: () => void
}

export default function Sidebar({
  collapsed,
  publicLinks,
  protectedLinks,
  currentUser,
  onToggle,
  onNavigate,
  onOpenProfile,
}: SidebarProps) {
  const [isHoveringButton, setIsHoveringButton] = useState(false)

  return (
    <aside className={`sidebar ${collapsed ? 'collapsed' : ''} ${isHoveringButton && collapsed ? 'button-hover' : ''}`}>
      <div className="sidebar-header">
        <img src={logoImage} alt="PromiseMarry Lab Logo" className="logo-image" />
        <strong>PromiseMarry Lab</strong>
        <button
          className="sidebar-expand-btn"
          type="button"
          aria-label={collapsed ? '사이드바 펼치기' : '사이드바 접기'}
          title={collapsed ? '사이드바 펼치기' : '사이드바 접기'}
          onClick={onToggle}
          onMouseEnter={() => setIsHoveringButton(true)}
          onMouseLeave={() => setIsHoveringButton(false)}
        >
          <span className="arrow" aria-hidden="true">{collapsed ? '»' : '«'}</span>
        </button>
      </div>

      <nav className="sidebar-menu">
        {publicLinks.map((item) => (
          <button
            key={item.label}
            className={`sidebar-menu-item ${item.active ? 'active' : ''}`}
            type="button"
            onClick={() => onNavigate(item)}
          >
            <span className="icon">{item.icon}</span>
            <span className="text">{item.label}</span>
          </button>
        ))}
      </nav>

      <div className="sidebar-divider"></div>

      <nav className="sidebar-menu">
        <div className="sidebar-section-title">주요 기능</div>
        {protectedLinks.map((item) => (
          <button
            key={item.label}
            className={`sidebar-menu-item ${item.active ? 'active' : ''}`}
            type="button"
            onClick={() => onNavigate(item)}
          >
            <span className="icon">{item.icon}</span>
            <span className="text">{item.label}</span>
          </button>
        ))}
      </nav>

      <div className="sidebar-menu" style={{ marginTop: 'auto', paddingTop: 0 }}>
        {currentUser && (
          <button
            className="sidebar-menu-item"
            type="button"
            style={{ cursor: 'pointer' }}
            onClick={onOpenProfile}
          >
            <span className="icon" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              {currentUser.profileImageUrl ? (
                <img
                  src={currentUser.profileImageUrl}
                  alt="프로필"
                  style={{ width: '24px', height: '24px', borderRadius: '50%', objectFit: 'cover' }}
                />
              ) : (
                <span>👤</span>
              )}
            </span>
            <span className="text">{currentUser.nickname}님</span>
          </button>
        )}
      </div>
    </aside>
  )
}
