// wedding-vue/src/views/HomeView.vue
<script setup lang="ts">
import HomeCalendar from '@/components/sections/HomeCalendar.vue'
</script>

<template>
  <div class="home-view">
    <div class="home-content">
      <HomeCalendar />
    </div>
  </div>
</template>

<style scoped>
.home-view {
  width: 100%;
  min-height: 100vh;
}

.home-content {
  padding: 16px;
  padding-bottom: 100px; /* 하단 네비게이션 공간 */
}

@media (max-width: 768px) {
  .home-content {
    padding: 12px;
    padding-bottom: 100px;
  }
}
</style>

// wedding-react/src/pages/HomeView.tsx
import React from 'react'
import HomeCalendar from '@/components/sections/HomeCalendar'
import '@/components/sections/HomeCalendar.css'
import './HomeView.css'

export default function HomeView() {
  return (
    <div className="home-view">
      <div className="home-content">
        <HomeCalendar />
      </div>
    </div>
  )
}
